[package]
name = "stardom"
version = "0.1.0"
edition = "2021"
authors.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
stardom-reactive = { version = "0.1.0", path = "../stardom-reactive" }
stardom-nodes = { version = "0.1.0", path = "../stardom-nodes" }
stardom-macros = { version = "0.1.0", path = "../stardom-macros" }

stardom-web = { version = "0.1.0", path = "../stardom-web" }
stardom-render = { version = "0.1.0", path = "../stardom-render" }
