pub const ATTRS: &[&str] = &[
    "abbr",
    "accept",
    "accept-charset",
    "accesskey",
    "action",
    "allow",
    "allowfullscreen",
    "alt",
    "as",
    "async",
    "autocapitalize",
    "autocomplete",
    "autofocus",
    "autoplay",
    "blocking",
    "charset",
    "checked",
    "cite",
    "class",
    "color",
    "cols",
    "colspan",
    "content",
    "contenteditable",
    "controls",
    "coords",
    "crossorigin",
    "data",
    "datetime",
    "decoding",
    "default",
    "defer",
    "dir",
    "dirname",
    "disabled",
    "download",
    "draggable",
    "enctype",
    "enterkeyhint",
    "fetchpriority",
    "for",
    "form",
    "formaction",
    "formenctype",
    "formmethod",
    "formnovalidate",
    "formtarget",
    "headers",
    "height",
    "hidden",
    "high",
    "href",
    "hreflang",
    "http-equiv",
    "id",
    "imagesizes",
    "imagesrcset",
    "inert",
    "inputmode",
    "integrity",
    "is",
    "ismap",
    "itemid",
    "itemprop",
    "itemref",
    "itemscope",
    "itemtype",
    "kind",
    "label",
    "lang",
    "list",
    "loading",
    "loop",
    "low",
    "max",
    "maxlength",
    "media",
    "method",
    "min",
    "minlength",
    "multiple",
    "muted",
    "name",
    "nomodule",
    "nonce",
    "novalidate",
    "open",
    "optimum",
    "pattern",
    "ping",
    "placeholder",
    "playsinline",
    "popover",
    "popovertarget",
    "popovertargetaction",
    "poster",
    "preload",
    "readonly",
    "referrerpolicy",
    "rel",
    "required",
    "reversed",
    "rows",
    "rowspan",
    "sandbox",
    "scope",
    "selected",
    "shadowrootmode",
    "shadowrootdelegatesfocus",
    "shape",
    "size",
    "sizes",
    "slot",
    "span",
    "spellcheck",
    "src",
    "srcdoc",
    "srclang",
    "srcset",
    "start",
    "step",
    "style",
    "tabindex",
    "target",
    "title",
    "translate",
    "type",
    "usemap",
    "value",
    "width",
    "wrap",
];

pub const EVENTS: &[(&str, &str)] = &[
    ("DOMContentLoaded", "Event"),
    ("afterprint", "Event"),
    ("beforeprint", "Event"),
    ("beforematch", "Event"),
    ("beforetoggle", "ToggleEvent"),
    ("beforeunload", "BeforeUnloadEvent"),
    ("blur", "Event"),
    ("cancel", "Event"),
    ("change", "Event"),
    ("click", "PointerEvent"),
    ("close", "Event"),
    ("connect", "MessageEvent"),
    ("contextlost", "Event"),
    ("contextrestored", "Event"),
    ("currententrychange", "NavigationCurrentEntryChangeEvent"),
    ("dispose", "Event"),
    ("error", "Event"),
    ("focus", "Event"),
    ("formdata", "FormDataEvent"),
    ("hashchange", "HashChangeEvent"),
    ("input", "Event"),
    ("invalid", "Event"),
    ("languagechange", "Event"),
    ("load", "Event"),
    ("message", "MessageEvent"),
    ("messageerror", "MessageEvent"),
    ("navigate", "NavigateEvent"),
    ("navigateerror", "ErrorEvent"),
    ("navigatesuccess", "Event"),
    ("offline", "Event"),
    ("online", "Event"),
    ("open", "Event"),
    ("pagehide", "PageTransitionEvent"),
    ("pagereveal", "PageRevealEvent"),
    ("pageshow", "PageTransitionEvent"),
    ("pointercancel", "PointerEvent"),
    ("popstate", "PopStateEvent"),
    ("readystatechange", "Event"),
    ("rejectionhandled", "PromiseRejectionEvent"),
    ("reset", "Event"),
    ("select", "Event"),
    ("storage", "StorageEvent"),
    ("submit", "SubmitEvent"),
    ("toggle", "ToggleEvent"),
    ("unhandledrejection", "PromiseRejectionEvent"),
    ("unload", "Event"),
    ("visibilitychange", "Event"),
    ("loadstart", "Event"),
    ("progress", "Event"),
    ("suspend", "Event"),
    ("abort", "Event"),
    ("emptied", "Event"),
    ("stalled", "Event"),
    ("addtrack", "TrackEvent"),
    ("removetrack", "TrackEvent"),
    ("cuechange", "Event"),
    ("enter", "Event"),
    ("exit", "Event"),
    ("dragstart", "DragEvent"),
    ("drag", "DragEvent"),
    ("dragenter", "DragEvent"),
    ("dragleave", "DragEvent"),
    ("dragover", "DragEvent"),
    ("drop", "DragEvent"),
    ("dragend", "DragEvent"),
];
