[package]
name = "stardom-web"
version = "0.1.0"
edition = "2021"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
stardom-nodes = { path = "../stardom-nodes" }

wasm-bindgen = { version = "0.2", features = ["enable-interning"] }
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"
features = [
  "Window",
  "Document",
  "Node",
  "Element",
  "Text",
  "Comment",
  "Range",
  "DocumentFragment",
  "NodeList",
  "Event"
]

[dev-dependencies]
stardom-reactive = { path = "../stardom-reactive" }
stardom-macros = { path = "../stardom-macros" }
wasm-bindgen-test = "0.3"
