[package]
name = "stardom"
version = "0.1.1"
edition = "2021"

[dependencies]
stardom-macros = { version = "0.1.1", path = "../stardom-macros" }
wasm-bindgen = { version = "0.2", features = ["enable-interning"] }
indexmap = "2"

[dependencies.web-sys]
version = "0.3"
features = [
  "Window",
  "Document",
  "Node",
  "Text",
  "Element",
  "Range",
  "DocumentFragment",
  "NodeList",
  "Event",
  "AddEventListenerOptions",

  # for generated events
  "BeforeUnloadEvent",
  "PointerEvent",
  "MessageEvent",
  "HashChangeEvent",
  "ErrorEvent",
  "PageTransitionEvent",
  "PopStateEvent",
  "PromiseRejectionEvent",
  "StorageEvent",
  "SubmitEvent",
  "TrackEvent",
  "DragEvent",
]

[dev-dependencies]
console_error_panic_hook = "0.1"
