[package]
name = "gen-dom"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ureq = "2"
scraper = "0.18"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

anyhow = "1"
