[package]
name = "stardom-nodes"
version = "0.1.0"
edition = "2021"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
stardom-macros = { version = "0.1.0", path = "../stardom-macros" }

wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = ["Event"]
