[package]
name = "stardom-macros"
version = "0.1.1"
edition = "2021"
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
paste = "1"
convert_case = "0.6"

