[package]
name = "stardom-macros"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
phf = { version = "0.11", features = ["macros"] }
convert_case = "0.6"
